version: 2.1

orbs:
  windows: circleci/windows@2.2.0
  
jobs:
  test:
    description: run unit tests
    executor: 
      name: windows/default #consider changing this to docker
      size: "medium" #medium by default
    steps:  # these steps arent tested
      - checkout
      - restore_cache: #these steps are on first job 
          keys:
            - dotnet-packages-v1-{{ checksum "Payroll Web App/Payroll Web App.csproj" }}
      - run:
          name: "Install project dependencies"
          command: dotnet.exe restore
      - save_cache:
          paths:
            - C:\Users\circleci\.nuget\packages  # i dont know if this exists
          key: dotnet-packages-v1-{{ checksum "Payroll Web App/Payroll Web App.csproj" }}
      - run:
          name: "Run Application Tests"
          command: dotnet.exe test -v n --results-directory:test_coverage --collect:"Code Coverage"
      - store_artifacts:
          path: C:\Users\circleci\project\test_coverage #this also does not exist locally
    
  build: 
    description: Build release config
    executor: 
      name: windows/default
      size: "medium"
    steps: 
      - checkout 
      - run:
          name: Build app in Release Config
          command: dotnet.exe build --configuration Release
          

workflows:
  build-and-test:
    jobs:
      - test
      - build:
          requires:
            - test
    
